
baseURL = "http://example.org/"
languageCode = "en-us"
title = "TJ's Class"
theme = "basic"
[Params]
author = "TJ Lamanna"
description = "My portfolio site"
gh_url = "https://api.github.com/users"
gh_user = "TLamanna"